base_model: /workspace/models/Llama-3.2-3B/
merge_method: ties
models:
- model: /workspace/models/llama-3.2-3b-wizard/
  parameters:
    density: 1
    weight: 0.5
- model: /workspace/models/experts/llama-3.2-3b-wizard-expert-math-100k/checkpoint-264
  parameters:
    density: 1
    weight: 0.5
